[Wed Mar 14 20:36:39 2012] [error] [client 79.0.20.242] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Wed Mar 14 20:36:39 2012] [error] [client 79.0.20.242] File does not exist: /var/www/people/ltw1218/html/apple-touch-icon-precomposed.png
[Wed Mar 14 20:36:39 2012] [error] [client 79.0.20.242] File does not exist: /var/www/people/ltw1218/html/apple-touch-icon.png
[Wed Mar 14 20:36:46 2012] [error] [client 79.0.20.242] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Wed Mar 14 20:36:46 2012] [error] [client 79.0.20.242] File does not exist: /var/www/people/ltw1218/html/apple-touch-icon-precomposed.png
[Wed Mar 14 20:36:46 2012] [error] [client 79.0.20.242] File does not exist: /var/www/people/ltw1218/html/apple-touch-icon.png
[Wed Mar 14 20:36:59 2012] [error] [client 79.0.20.242] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Wed Mar 14 20:36:59 2012] [error] [client 79.0.20.242] File does not exist: /var/www/people/ltw1218/html/apple-touch-icon-precomposed.png
[Wed Mar 14 20:36:59 2012] [error] [client 79.0.20.242] File does not exist: /var/www/people/ltw1218/html/apple-touch-icon.png
[Wed Mar 14 20:37:00 2012] [error] [client 79.0.20.242] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Wed Mar 14 20:37:00 2012] [error] [client 79.0.20.242] File does not exist: /var/www/people/ltw1218/html/apple-touch-icon-precomposed.png
[Wed Mar 14 20:37:00 2012] [error] [client 79.0.20.242] File does not exist: /var/www/people/ltw1218/html/apple-touch-icon.png
[Thu Mar 15 12:41:31 2012] [error] [client 188.11.9.62] (13)Permission denied: exec of '/var/www/people/ltw1218/cgi-bin/prova.py' failed
[Thu Mar 15 12:41:31 2012] [error] [client 188.11.9.62] Premature end of script headers: prova.py
[Thu Mar 15 12:41:32 2012] [error] [client 188.11.9.62] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 12:46:07 2012] [error] [client 188.11.9.62] (13)Permission denied: exec of '/var/www/people/ltw1218/cgi-bin/prova.py' failed
[Thu Mar 15 12:46:07 2012] [error] [client 188.11.9.62] Premature end of script headers: prova.py
[Thu Mar 15 12:46:07 2012] [error] [client 188.11.9.62] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 12:46:10 2012] [error] [client 188.11.9.62] attempt to invoke directory as script: /var/www/people/ltw1218/cgi-bin/
[Thu Mar 15 12:46:11 2012] [error] [client 188.11.9.62] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 12:46:20 2012] [error] [client 188.11.9.62] (13)Permission denied: exec of '/var/www/people/ltw1218/cgi-bin/prova.py' failed
[Thu Mar 15 12:46:20 2012] [error] [client 188.11.9.62] Premature end of script headers: prova.py
[Thu Mar 15 12:46:21 2012] [error] [client 188.11.9.62] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 12:50:27 2012] [error] [client 188.11.9.62] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 12:50:28 2012] [error] [client 188.11.9.62] mod_python (pid=21305, interpreter='ltw1218.web.cs.unibo.it', phase='PythonHandler', handler='mod_python.publisher'): Application error
[Thu Mar 15 12:50:28 2012] [error] [client 188.11.9.62] ServerName: 'ltw1218.web.cs.unibo.it'
[Thu Mar 15 12:50:28 2012] [error] [client 188.11.9.62] DocumentRoot: '/var/www/people/ltw1218/html'
[Thu Mar 15 12:50:28 2012] [error] [client 188.11.9.62] URI: '/cgi-bin/prova.py'
[Thu Mar 15 12:50:28 2012] [error] [client 188.11.9.62] Location: None
[Thu Mar 15 12:50:28 2012] [error] [client 188.11.9.62] Directory: '/var/www/people/ltw1218/cgi-bin/'
[Thu Mar 15 12:50:28 2012] [error] [client 188.11.9.62] Filename: '/var/www/people/ltw1218/cgi-bin/prova.py'
[Thu Mar 15 12:50:28 2012] [error] [client 188.11.9.62] PathInfo: ''
[Thu Mar 15 12:50:28 2012] [error] [client 188.11.9.62] Traceback (most recent call last):
[Thu Mar 15 12:50:28 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Thu Mar 15 12:50:28 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Thu Mar 15 12:50:28 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Thu Mar 15 12:50:28 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/publisher.py", line 204, in handler\n    module = page_cache[req]
[Thu Mar 15 12:50:28 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1059, in __getitem__\n    return import_module(req.filename)
[Thu Mar 15 12:50:28 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 296, in import_module\n    log, import_path)
[Thu Mar 15 12:50:28 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 680, in import_module\n    execfile(file, module.__dict__)
[Thu Mar 15 12:50:28 2012] [error] [client 188.11.9.62]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 9
[Thu Mar 15 12:50:28 2012] [error] [client 188.11.9.62]     return s
[Thu Mar 15 12:50:28 2012] [error] [client 188.11.9.62] SyntaxError: 'return' outside function
[Thu Mar 15 12:50:28 2012] [error] [client 188.11.9.62] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 12:51:53 2012] [error] [client 188.11.9.62] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 12:59:00 2012] [error] [client 188.11.9.62] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 12:59:00 2012] [error] [client 188.11.9.62] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:04:21 2012] [error] [client 188.11.9.62] mod_python (pid=21946, interpreter='ltw1218.web.cs.unibo.it', phase='PythonHandler', handler='mod_python.publisher'): Application error
[Thu Mar 15 13:04:21 2012] [error] [client 188.11.9.62] ServerName: 'ltw1218.web.cs.unibo.it'
[Thu Mar 15 13:04:21 2012] [error] [client 188.11.9.62] DocumentRoot: '/var/www/people/ltw1218/html'
[Thu Mar 15 13:04:21 2012] [error] [client 188.11.9.62] URI: '/cgi-bin/prova.py'
[Thu Mar 15 13:04:21 2012] [error] [client 188.11.9.62] Location: None
[Thu Mar 15 13:04:21 2012] [error] [client 188.11.9.62] Directory: '/var/www/people/ltw1218/cgi-bin/'
[Thu Mar 15 13:04:21 2012] [error] [client 188.11.9.62] Filename: '/var/www/people/ltw1218/cgi-bin/prova.py'
[Thu Mar 15 13:04:21 2012] [error] [client 188.11.9.62] PathInfo: ''
[Thu Mar 15 13:04:21 2012] [error] [client 188.11.9.62] Traceback (most recent call last):
[Thu Mar 15 13:04:21 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Thu Mar 15 13:04:21 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Thu Mar 15 13:04:21 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Thu Mar 15 13:04:21 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/publisher.py", line 204, in handler\n    module = page_cache[req]
[Thu Mar 15 13:04:21 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1059, in __getitem__\n    return import_module(req.filename)
[Thu Mar 15 13:04:21 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 296, in import_module\n    log, import_path)
[Thu Mar 15 13:04:21 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 680, in import_module\n    execfile(file, module.__dict__)
[Thu Mar 15 13:04:21 2012] [error] [client 188.11.9.62]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 6
[Thu Mar 15 13:04:21 2012] [error] [client 188.11.9.62]     print "%s = %s" % (key, fs[key].value)
[Thu Mar 15 13:04:21 2012] [error] [client 188.11.9.62]         ^
[Thu Mar 15 13:04:21 2012] [error] [client 188.11.9.62] IndentationError: expected an indented block
[Thu Mar 15 13:04:22 2012] [error] [client 188.11.9.62] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62] mod_python (pid=21972, interpreter='ltw1218.web.cs.unibo.it', phase='PythonHandler', handler='mod_python.publisher'): Application error
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62] ServerName: 'ltw1218.web.cs.unibo.it'
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62] DocumentRoot: '/var/www/people/ltw1218/html'
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62] URI: '/cgi-bin/prova.py'
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62] Location: None
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62] Directory: '/var/www/people/ltw1218/cgi-bin/'
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62] Filename: '/var/www/people/ltw1218/cgi-bin/prova.py'
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62] PathInfo: ''
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62] Traceback (most recent call last):
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/publisher.py", line 204, in handler\n    module = page_cache[req]
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1059, in __getitem__\n    return import_module(req.filename)
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 296, in import_module\n    log, import_path)
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 680, in import_module\n    execfile(file, module.__dict__)
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 5
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62]     for key in fs.keys():
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62]    ^
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62] IndentationError: unexpected indent
[Thu Mar 15 13:04:49 2012] [error] [client 188.11.9.62] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:05:03 2012] [error] [client 188.11.9.62] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:05:15 2012] [error] [client 188.11.9.62] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:08:55 2012] [error] [client 188.11.9.62] mod_python (pid=22166, interpreter='ltw1218.web.cs.unibo.it', phase='PythonHandler', handler='mod_python.publisher'): Application error
[Thu Mar 15 13:08:55 2012] [error] [client 188.11.9.62] ServerName: 'ltw1218.web.cs.unibo.it'
[Thu Mar 15 13:08:55 2012] [error] [client 188.11.9.62] DocumentRoot: '/var/www/people/ltw1218/html'
[Thu Mar 15 13:08:55 2012] [error] [client 188.11.9.62] URI: '/cgi-bin/prova.py'
[Thu Mar 15 13:08:55 2012] [error] [client 188.11.9.62] Location: None
[Thu Mar 15 13:08:55 2012] [error] [client 188.11.9.62] Directory: '/var/www/people/ltw1218/cgi-bin/'
[Thu Mar 15 13:08:55 2012] [error] [client 188.11.9.62] Filename: '/var/www/people/ltw1218/cgi-bin/prova.py'
[Thu Mar 15 13:08:55 2012] [error] [client 188.11.9.62] PathInfo: ''
[Thu Mar 15 13:08:55 2012] [error] [client 188.11.9.62] Traceback (most recent call last):
[Thu Mar 15 13:08:55 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Thu Mar 15 13:08:55 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Thu Mar 15 13:08:55 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Thu Mar 15 13:08:55 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/publisher.py", line 204, in handler\n    module = page_cache[req]
[Thu Mar 15 13:08:55 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1059, in __getitem__\n    return import_module(req.filename)
[Thu Mar 15 13:08:55 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 296, in import_module\n    log, import_path)
[Thu Mar 15 13:08:55 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 680, in import_module\n    execfile(file, module.__dict__)
[Thu Mar 15 13:08:55 2012] [error] [client 188.11.9.62]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 7
[Thu Mar 15 13:08:55 2012] [error] [client 188.11.9.62]     return key;
[Thu Mar 15 13:08:55 2012] [error] [client 188.11.9.62] SyntaxError: 'return' outside function
[Thu Mar 15 13:08:56 2012] [error] [client 188.11.9.62] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:09:50 2012] [error] [client 188.11.9.62] mod_python (pid=22212, interpreter='ltw1218.web.cs.unibo.it', phase='PythonHandler', handler='mod_python.publisher'): Application error
[Thu Mar 15 13:09:50 2012] [error] [client 188.11.9.62] ServerName: 'ltw1218.web.cs.unibo.it'
[Thu Mar 15 13:09:50 2012] [error] [client 188.11.9.62] DocumentRoot: '/var/www/people/ltw1218/html'
[Thu Mar 15 13:09:50 2012] [error] [client 188.11.9.62] URI: '/cgi-bin/prova.py'
[Thu Mar 15 13:09:50 2012] [error] [client 188.11.9.62] Location: None
[Thu Mar 15 13:09:50 2012] [error] [client 188.11.9.62] Directory: '/var/www/people/ltw1218/cgi-bin/'
[Thu Mar 15 13:09:50 2012] [error] [client 188.11.9.62] Filename: '/var/www/people/ltw1218/cgi-bin/prova.py'
[Thu Mar 15 13:09:50 2012] [error] [client 188.11.9.62] PathInfo: ''
[Thu Mar 15 13:09:50 2012] [error] [client 188.11.9.62] Traceback (most recent call last):
[Thu Mar 15 13:09:50 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Thu Mar 15 13:09:50 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Thu Mar 15 13:09:50 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Thu Mar 15 13:09:50 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/publisher.py", line 204, in handler\n    module = page_cache[req]
[Thu Mar 15 13:09:50 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1059, in __getitem__\n    return import_module(req.filename)
[Thu Mar 15 13:09:50 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 296, in import_module\n    log, import_path)
[Thu Mar 15 13:09:50 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 680, in import_module\n    execfile(file, module.__dict__)
[Thu Mar 15 13:09:50 2012] [error] [client 188.11.9.62]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 4
[Thu Mar 15 13:09:50 2012] [error] [client 188.11.9.62]     define index()
[Thu Mar 15 13:09:50 2012] [error] [client 188.11.9.62]                ^
[Thu Mar 15 13:09:50 2012] [error] [client 188.11.9.62] SyntaxError: invalid syntax
[Thu Mar 15 13:09:51 2012] [error] [client 188.11.9.62] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62] mod_python (pid=22381, interpreter='ltw1218.web.cs.unibo.it', phase='PythonHandler', handler='mod_python.publisher'): Application error
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62] ServerName: 'ltw1218.web.cs.unibo.it'
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62] DocumentRoot: '/var/www/people/ltw1218/html'
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62] URI: '/cgi-bin/prova.py'
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62] Location: None
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62] Directory: '/var/www/people/ltw1218/cgi-bin/'
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62] Filename: '/var/www/people/ltw1218/cgi-bin/prova.py'
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62] PathInfo: ''
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62] Traceback (most recent call last):
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/publisher.py", line 204, in handler\n    module = page_cache[req]
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1059, in __getitem__\n    return import_module(req.filename)
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 296, in import_module\n    log, import_path)
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 680, in import_module\n    execfile(file, module.__dict__)
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 4
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62]     define index()
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62]                ^
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62] SyntaxError: invalid syntax
[Thu Mar 15 13:10:07 2012] [error] [client 188.11.9.62] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:10:42 2012] [error] [client 188.11.9.62] mod_python (pid=22391, interpreter='ltw1218.web.cs.unibo.it', phase='PythonHandler', handler='mod_python.publisher'): Application error
[Thu Mar 15 13:10:42 2012] [error] [client 188.11.9.62] ServerName: 'ltw1218.web.cs.unibo.it'
[Thu Mar 15 13:10:42 2012] [error] [client 188.11.9.62] DocumentRoot: '/var/www/people/ltw1218/html'
[Thu Mar 15 13:10:42 2012] [error] [client 188.11.9.62] URI: '/cgi-bin/prova.py'
[Thu Mar 15 13:10:42 2012] [error] [client 188.11.9.62] Location: None
[Thu Mar 15 13:10:42 2012] [error] [client 188.11.9.62] Directory: '/var/www/people/ltw1218/cgi-bin/'
[Thu Mar 15 13:10:42 2012] [error] [client 188.11.9.62] Filename: '/var/www/people/ltw1218/cgi-bin/prova.py'
[Thu Mar 15 13:10:42 2012] [error] [client 188.11.9.62] PathInfo: ''
[Thu Mar 15 13:10:42 2012] [error] [client 188.11.9.62] Traceback (most recent call last):
[Thu Mar 15 13:10:42 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Thu Mar 15 13:10:42 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Thu Mar 15 13:10:42 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Thu Mar 15 13:10:42 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/publisher.py", line 204, in handler\n    module = page_cache[req]
[Thu Mar 15 13:10:42 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1059, in __getitem__\n    return import_module(req.filename)
[Thu Mar 15 13:10:42 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 296, in import_module\n    log, import_path)
[Thu Mar 15 13:10:42 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 680, in import_module\n    execfile(file, module.__dict__)
[Thu Mar 15 13:10:42 2012] [error] [client 188.11.9.62]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 3
[Thu Mar 15 13:10:42 2012] [error] [client 188.11.9.62]     define index()
[Thu Mar 15 13:10:42 2012] [error] [client 188.11.9.62]                ^
[Thu Mar 15 13:10:42 2012] [error] [client 188.11.9.62] SyntaxError: invalid syntax
[Thu Mar 15 13:10:43 2012] [error] [client 188.11.9.62] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:12:05 2012] [error] [client 188.11.9.62] mod_python (pid=22414, interpreter='ltw1218.web.cs.unibo.it', phase='PythonHandler', handler='mod_python.publisher'): Application error
[Thu Mar 15 13:12:05 2012] [error] [client 188.11.9.62] ServerName: 'ltw1218.web.cs.unibo.it'
[Thu Mar 15 13:12:05 2012] [error] [client 188.11.9.62] DocumentRoot: '/var/www/people/ltw1218/html'
[Thu Mar 15 13:12:05 2012] [error] [client 188.11.9.62] URI: '/cgi-bin/prova.py'
[Thu Mar 15 13:12:05 2012] [error] [client 188.11.9.62] Location: None
[Thu Mar 15 13:12:05 2012] [error] [client 188.11.9.62] Directory: '/var/www/people/ltw1218/cgi-bin/'
[Thu Mar 15 13:12:05 2012] [error] [client 188.11.9.62] Filename: '/var/www/people/ltw1218/cgi-bin/prova.py'
[Thu Mar 15 13:12:05 2012] [error] [client 188.11.9.62] PathInfo: ''
[Thu Mar 15 13:12:05 2012] [error] [client 188.11.9.62] Traceback (most recent call last):
[Thu Mar 15 13:12:05 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Thu Mar 15 13:12:05 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Thu Mar 15 13:12:05 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Thu Mar 15 13:12:05 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/publisher.py", line 204, in handler\n    module = page_cache[req]
[Thu Mar 15 13:12:05 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1059, in __getitem__\n    return import_module(req.filename)
[Thu Mar 15 13:12:05 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 296, in import_module\n    log, import_path)
[Thu Mar 15 13:12:05 2012] [error] [client 188.11.9.62]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 680, in import_module\n    execfile(file, module.__dict__)
[Thu Mar 15 13:12:05 2012] [error] [client 188.11.9.62]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 3
[Thu Mar 15 13:12:05 2012] [error] [client 188.11.9.62]     define index():
[Thu Mar 15 13:12:05 2012] [error] [client 188.11.9.62]                ^
[Thu Mar 15 13:12:05 2012] [error] [client 188.11.9.62] SyntaxError: invalid syntax
[Thu Mar 15 13:12:06 2012] [error] [client 188.11.9.62] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:13:00 2012] [error] [client 188.11.9.62] mod_python.publisher: nothing to publish.
[Thu Mar 15 13:13:07 2012] [error] [client 188.11.9.62] mod_python.publisher: nothing to publish.
[Thu Mar 15 13:13:21 2012] [error] [client 188.11.9.62] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:46:16 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:47:03 2012] [error] [client 87.10.52.250] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:52:42 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:52:52 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:52:57 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:53:50 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:53:55 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:55:07 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:55:44 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:56:09 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:56:33 2012] [error] [client 79.12.23.94] script not found or unable to stat: /var/www/people/ltw1218/html/prova.py
[Thu Mar 15 13:56:33 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:56:35 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 13:57:43 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:02:37 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:02:38 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:05:16 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:06:19 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:06:25 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:11:52 2012] [alert] [client 79.12.23.94] /var/www/people/ltw1218/cgi-bin/.htaccess: Options not allowed here
[Thu Mar 15 14:11:53 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:12:01 2012] [alert] [client 79.12.23.94] /var/www/people/ltw1218/cgi-bin/.htaccess: Options not allowed here
[Thu Mar 15 14:12:02 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:12:45 2012] [alert] [client 79.12.23.94] /var/www/people/ltw1218/cgi-bin/.htaccess: Options not allowed here
[Thu Mar 15 14:12:46 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:15:39 2012] [error] [client 79.12.23.94] (8)Exec format error: exec of '/var/www/people/ltw1218/cgi-bin/prova.py' failed
[Thu Mar 15 14:15:39 2012] [error] [client 79.12.23.94] Premature end of script headers: prova.py
[Thu Mar 15 14:15:40 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:15:41 2012] [error] [client 79.12.23.94] (8)Exec format error: exec of '/var/www/people/ltw1218/cgi-bin/prova.py' failed
[Thu Mar 15 14:15:41 2012] [error] [client 79.12.23.94] Premature end of script headers: prova.py
[Thu Mar 15 14:15:42 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:28:25 2012] [alert] [client 79.12.23.94] /var/www/people/ltw1218/cgi-bin/.htaccess: <Directory not allowed here
[Thu Mar 15 14:28:26 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:28:28 2012] [alert] [client 79.12.23.94] /var/www/people/ltw1218/cgi-bin/.htaccess: <Directory not allowed here
[Thu Mar 15 14:28:28 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:28:38 2012] [alert] [client 79.12.23.94] /var/www/people/ltw1218/cgi-bin/.htaccess: <Directory not allowed here
[Thu Mar 15 14:28:39 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:28:46 2012] [alert] [client 79.12.23.94] /var/www/people/ltw1218/cgi-bin/.htaccess: <Directory not allowed here
[Thu Mar 15 14:28:47 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:32:20 2012] [alert] [client 79.12.23.94] /var/www/people/ltw1218/cgi-bin/.htaccess: <Directory not allowed here
[Thu Mar 15 14:32:21 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:33:19 2012] [alert] [client 79.12.23.94] /var/www/people/ltw1218/cgi-bin/.htaccess: <Directory not allowed here
[Thu Mar 15 14:33:20 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:33:24 2012] [alert] [client 79.12.23.94] /var/www/people/ltw1218/cgi-bin/.htaccess: <Directory not allowed here
[Thu Mar 15 14:33:24 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:36:16 2012] [alert] [client 79.12.23.94] /var/www/people/ltw1218/cgi-bin/.htaccess: Options not allowed here
[Thu Mar 15 14:36:17 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:41:20 2012] [error] [client 79.12.23.94] mod_python (pid=27307, interpreter='ltw1218.web.cs.unibo.it', phase='PythonHandler', handler='mptest'): Application error
[Thu Mar 15 14:41:20 2012] [error] [client 79.12.23.94] ServerName: 'ltw1218.web.cs.unibo.it'
[Thu Mar 15 14:41:20 2012] [error] [client 79.12.23.94] DocumentRoot: '/var/www/people/ltw1218/html'
[Thu Mar 15 14:41:20 2012] [error] [client 79.12.23.94] URI: '/cgi-bin/prova.py'
[Thu Mar 15 14:41:20 2012] [error] [client 79.12.23.94] Location: None
[Thu Mar 15 14:41:20 2012] [error] [client 79.12.23.94] Directory: '/var/www/people/ltw1218/cgi-bin/'
[Thu Mar 15 14:41:20 2012] [error] [client 79.12.23.94] Filename: '/var/www/people/ltw1218/cgi-bin/prova.py'
[Thu Mar 15 14:41:20 2012] [error] [client 79.12.23.94] PathInfo: ''
[Thu Mar 15 14:41:20 2012] [error] [client 79.12.23.94] Traceback (most recent call last):
[Thu Mar 15 14:41:20 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Thu Mar 15 14:41:20 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1202, in _process_target\n    module = import_module(module_name, path=path)
[Thu Mar 15 14:41:20 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 296, in import_module\n    log, import_path)
[Thu Mar 15 14:41:20 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 680, in import_module\n    execfile(file, module.__dict__)
[Thu Mar 15 14:41:20 2012] [error] [client 79.12.23.94]   File "/var/www/people/ltw1218/cgi-bin/mptest.py", line 1
[Thu Mar 15 14:41:20 2012] [error] [client 79.12.23.94]     from mod_python import apache
[Thu Mar 15 14:41:20 2012] [error] [client 79.12.23.94]    ^
[Thu Mar 15 14:41:20 2012] [error] [client 79.12.23.94] IndentationError: unexpected indent
[Thu Mar 15 14:41:20 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:43:12 2012] [error] [client 79.12.23.94] handler
[Thu Mar 15 14:43:13 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:44:12 2012] [error] [client 79.12.23.94] mod_python (pid=27360, interpreter='ltw1218.web.cs.unibo.it', phase='PythonHandler', handler='mod_python'): Application error
[Thu Mar 15 14:44:12 2012] [error] [client 79.12.23.94] ServerName: 'ltw1218.web.cs.unibo.it'
[Thu Mar 15 14:44:12 2012] [error] [client 79.12.23.94] DocumentRoot: '/var/www/people/ltw1218/html'
[Thu Mar 15 14:44:12 2012] [error] [client 79.12.23.94] URI: '/cgi-bin/prova.py'
[Thu Mar 15 14:44:12 2012] [error] [client 79.12.23.94] Location: None
[Thu Mar 15 14:44:12 2012] [error] [client 79.12.23.94] Directory: '/var/www/people/ltw1218/cgi-bin/'
[Thu Mar 15 14:44:12 2012] [error] [client 79.12.23.94] Filename: '/var/www/people/ltw1218/cgi-bin/prova.py'
[Thu Mar 15 14:44:12 2012] [error] [client 79.12.23.94] PathInfo: ''
[Thu Mar 15 14:44:12 2012] [error] [client 79.12.23.94] Traceback (most recent call last):
[Thu Mar 15 14:44:12 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Thu Mar 15 14:44:12 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1206, in _process_target\n    object = apache.resolve_object(module, object_str, arg, silent=silent)
[Thu Mar 15 14:44:12 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/dist-packages/mod_python/apache.py", line 696, in resolve_object\n    raise AttributeError, s
[Thu Mar 15 14:44:12 2012] [error] [client 79.12.23.94] AttributeError: module '/usr/lib/python2.6/dist-packages/mod_python/__init__.pyc' contains no 'handler'
[Thu Mar 15 14:44:13 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:47:11 2012] [error] [client 79.12.23.94] mod_python (pid=27550, interpreter='ltw1218.web.cs.unibo.it', phase='PythonHandler', handler='mod_python'): Application error
[Thu Mar 15 14:47:11 2012] [error] [client 79.12.23.94] ServerName: 'ltw1218.web.cs.unibo.it'
[Thu Mar 15 14:47:11 2012] [error] [client 79.12.23.94] DocumentRoot: '/var/www/people/ltw1218/html'
[Thu Mar 15 14:47:11 2012] [error] [client 79.12.23.94] URI: '/cgi-bin/prova.py'
[Thu Mar 15 14:47:11 2012] [error] [client 79.12.23.94] Location: None
[Thu Mar 15 14:47:11 2012] [error] [client 79.12.23.94] Directory: '/var/www/people/ltw1218/cgi-bin/'
[Thu Mar 15 14:47:11 2012] [error] [client 79.12.23.94] Filename: '/var/www/people/ltw1218/cgi-bin/prova.py'
[Thu Mar 15 14:47:11 2012] [error] [client 79.12.23.94] PathInfo: ''
[Thu Mar 15 14:47:11 2012] [error] [client 79.12.23.94] Traceback (most recent call last):
[Thu Mar 15 14:47:11 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Thu Mar 15 14:47:11 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1206, in _process_target\n    object = apache.resolve_object(module, object_str, arg, silent=silent)
[Thu Mar 15 14:47:11 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/dist-packages/mod_python/apache.py", line 696, in resolve_object\n    raise AttributeError, s
[Thu Mar 15 14:47:11 2012] [error] [client 79.12.23.94] AttributeError: module '/usr/lib/python2.6/dist-packages/mod_python/__init__.pyc' contains no 'handler'
[Thu Mar 15 14:47:11 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:47:37 2012] [error] [client 79.12.23.94] (8)Exec format error: exec of '/var/www/people/ltw1218/cgi-bin/prova.py' failed
[Thu Mar 15 14:47:37 2012] [error] [client 79.12.23.94] Premature end of script headers: prova.py
[Thu Mar 15 14:47:38 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:47:39 2012] [error] [client 79.12.23.94] (8)Exec format error: exec of '/var/www/people/ltw1218/cgi-bin/prova.py' failed
[Thu Mar 15 14:47:39 2012] [error] [client 79.12.23.94] Premature end of script headers: prova.py
[Thu Mar 15 14:47:39 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:49:10 2012] [error] [client 79.12.23.94] mod_python (pid=27610, interpreter='ltw1218.web.cs.unibo.it', phase='PythonHandler', handler='python'): Application error
[Thu Mar 15 14:49:10 2012] [error] [client 79.12.23.94] ServerName: 'ltw1218.web.cs.unibo.it'
[Thu Mar 15 14:49:10 2012] [error] [client 79.12.23.94] DocumentRoot: '/var/www/people/ltw1218/html'
[Thu Mar 15 14:49:10 2012] [error] [client 79.12.23.94] URI: '/cgi-bin/prova.py'
[Thu Mar 15 14:49:10 2012] [error] [client 79.12.23.94] Location: None
[Thu Mar 15 14:49:10 2012] [error] [client 79.12.23.94] Directory: '/var/www/people/ltw1218/cgi-bin/'
[Thu Mar 15 14:49:10 2012] [error] [client 79.12.23.94] Filename: '/var/www/people/ltw1218/cgi-bin/prova.py'
[Thu Mar 15 14:49:10 2012] [error] [client 79.12.23.94] PathInfo: ''
[Thu Mar 15 14:49:10 2012] [error] [client 79.12.23.94] Traceback (most recent call last):
[Thu Mar 15 14:49:10 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Thu Mar 15 14:49:10 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1202, in _process_target\n    module = import_module(module_name, path=path)
[Thu Mar 15 14:49:10 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 304, in import_module\n    return __import__(module_name, {}, {}, ['*'])
[Thu Mar 15 14:49:10 2012] [error] [client 79.12.23.94] ImportError: No module named python
[Thu Mar 15 14:49:11 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:49:28 2012] [error] [client 79.12.23.94] mod_python (pid=27618, interpreter='ltw1218.web.cs.unibo.it', phase='PythonHandler', handler='mod_python'): Application error
[Thu Mar 15 14:49:28 2012] [error] [client 79.12.23.94] ServerName: 'ltw1218.web.cs.unibo.it'
[Thu Mar 15 14:49:28 2012] [error] [client 79.12.23.94] DocumentRoot: '/var/www/people/ltw1218/html'
[Thu Mar 15 14:49:28 2012] [error] [client 79.12.23.94] URI: '/cgi-bin/prova.py'
[Thu Mar 15 14:49:28 2012] [error] [client 79.12.23.94] Location: None
[Thu Mar 15 14:49:28 2012] [error] [client 79.12.23.94] Directory: '/var/www/people/ltw1218/cgi-bin/'
[Thu Mar 15 14:49:28 2012] [error] [client 79.12.23.94] Filename: '/var/www/people/ltw1218/cgi-bin/prova.py'
[Thu Mar 15 14:49:28 2012] [error] [client 79.12.23.94] PathInfo: ''
[Thu Mar 15 14:49:28 2012] [error] [client 79.12.23.94] Traceback (most recent call last):
[Thu Mar 15 14:49:28 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Thu Mar 15 14:49:28 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1206, in _process_target\n    object = apache.resolve_object(module, object_str, arg, silent=silent)
[Thu Mar 15 14:49:28 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/dist-packages/mod_python/apache.py", line 696, in resolve_object\n    raise AttributeError, s
[Thu Mar 15 14:49:28 2012] [error] [client 79.12.23.94] AttributeError: module '/usr/lib/python2.6/dist-packages/mod_python/__init__.pyc' contains no 'handler'
[Thu Mar 15 14:49:28 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:54:40 2012] [error] [client 79.12.23.94] (8)Exec format error: exec of '/var/www/people/ltw1218/cgi-bin/prova.py' failed
[Thu Mar 15 14:54:40 2012] [error] [client 79.12.23.94] Premature end of script headers: prova.py
[Thu Mar 15 14:54:41 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:54:49 2012] [error] [client 79.12.23.94] (8)Exec format error: exec of '/var/www/people/ltw1218/cgi-bin/prova.py' failed
[Thu Mar 15 14:54:49 2012] [error] [client 79.12.23.94] Premature end of script headers: prova.py
[Thu Mar 15 14:54:49 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:54:56 2012] [error] [client 79.12.23.94] (8)Exec format error: exec of '/var/www/people/ltw1218/cgi-bin/prova.py' failed
[Thu Mar 15 14:54:56 2012] [error] [client 79.12.23.94] Premature end of script headers: prova.py
[Thu Mar 15 14:54:57 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:58:13 2012] [error] [client 79.12.23.94] (8)Exec format error: exec of '/var/www/people/ltw1218/cgi-bin/prova.py' failed
[Thu Mar 15 14:58:13 2012] [error] [client 79.12.23.94] Premature end of script headers: prova.py
[Thu Mar 15 14:58:14 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 14:58:16 2012] [error] [client 79.12.23.94] (8)Exec format error: exec of '/var/www/people/ltw1218/cgi-bin/prova.py' failed
[Thu Mar 15 14:58:16 2012] [error] [client 79.12.23.94] Premature end of script headers: prova.py
[Thu Mar 15 14:58:17 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 15:00:09 2012] [error] [client 79.12.23.94] (8)Exec format error: exec of '/var/www/people/ltw1218/cgi-bin/prova.py' failed
[Thu Mar 15 15:00:09 2012] [error] [client 79.12.23.94] Premature end of script headers: prova.py
[Thu Mar 15 15:00:10 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 15:03:01 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 15:05:24 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 15:05:30 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 15:07:11 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 15:07:17 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 15:13:11 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 15:13:51 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 15:14:09 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 15:14:23 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 15:25:16 2012] [error] [client 130.136.46.13] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 15:30:56 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 15:31:06 2012] [error] [client 82.58.26.198] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 15:31:06 2012] [error] [client 82.58.26.198] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 15:31:06 2012] [error] [client 82.58.26.198] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 15:52:31 2012] [error] [client 93.48.44.243] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Thu Mar 15 15:52:31 2012] [error] [client 93.48.44.243] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 13:41:09 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 13:41:12 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 13:42:34 2012] [error] [client 79.32.60.2] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 14:35:19 2012] [error] [client 79.32.60.2] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 14:35:36 2012] [error] [client 79.32.60.2] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 15:47:26 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 15:59:12 2012] [error] [client 79.12.23.94] Traceback (most recent call last):
[Fri Mar 16 15:59:12 2012] [error] [client 79.12.23.94]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 15, in <module>
[Fri Mar 16 15:59:12 2012] [error] [client 79.12.23.94]     main()
[Fri Mar 16 15:59:12 2012] [error] [client 79.12.23.94]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 12, in main
[Fri Mar 16 15:59:12 2012] [error] [client 79.12.23.94]     print("nome not found" % fs["nome"].value)
[Fri Mar 16 15:59:12 2012] [error] [client 79.12.23.94] TypeError: not all arguments converted during string formatting
[Fri Mar 16 15:59:13 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 15:59:54 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:00:10 2012] [error] [client 79.12.23.94] Traceback (most recent call last):
[Fri Mar 16 16:00:10 2012] [error] [client 79.12.23.94]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 15, in <module>
[Fri Mar 16 16:00:10 2012] [error] [client 79.12.23.94]     main()
[Fri Mar 16 16:00:10 2012] [error] [client 79.12.23.94]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 10, in main
[Fri Mar 16 16:00:10 2012] [error] [client 79.12.23.94]     print("%s" % fs["nome"].value)
[Fri Mar 16 16:00:10 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/cgi.py", line 541, in __getitem__
[Fri Mar 16 16:00:10 2012] [error] [client 79.12.23.94]     raise KeyError, key
[Fri Mar 16 16:00:10 2012] [error] [client 79.12.23.94] KeyError: 'nome'
[Fri Mar 16 16:00:10 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:00:14 2012] [error] [client 79.12.23.94] Traceback (most recent call last):
[Fri Mar 16 16:00:14 2012] [error] [client 79.12.23.94]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 15, in <module>
[Fri Mar 16 16:00:14 2012] [error] [client 79.12.23.94]     main()
[Fri Mar 16 16:00:14 2012] [error] [client 79.12.23.94]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 10, in main
[Fri Mar 16 16:00:14 2012] [error] [client 79.12.23.94]     print("%s" % fs["nome"].value)
[Fri Mar 16 16:00:14 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/cgi.py", line 541, in __getitem__
[Fri Mar 16 16:00:14 2012] [error] [client 79.12.23.94]     raise KeyError, key
[Fri Mar 16 16:00:14 2012] [error] [client 79.12.23.94] KeyError: 'nome'
[Fri Mar 16 16:00:14 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:02:10 2012] [error] [client 79.12.23.94] Traceback (most recent call last):
[Fri Mar 16 16:02:10 2012] [error] [client 79.12.23.94]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 15, in <module>
[Fri Mar 16 16:02:10 2012] [error] [client 79.12.23.94]     main()
[Fri Mar 16 16:02:10 2012] [error] [client 79.12.23.94]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 10, in main
[Fri Mar 16 16:02:10 2012] [error] [client 79.12.23.94]     print "%s" % fs["nome"].value
[Fri Mar 16 16:02:10 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/cgi.py", line 541, in __getitem__
[Fri Mar 16 16:02:10 2012] [error] [client 79.12.23.94]     raise KeyError, key
[Fri Mar 16 16:02:10 2012] [error] [client 79.12.23.94] KeyError: 'nome'
[Fri Mar 16 16:02:10 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:02:11 2012] [error] [client 79.12.23.94] Traceback (most recent call last):
[Fri Mar 16 16:02:11 2012] [error] [client 79.12.23.94]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 15, in <module>
[Fri Mar 16 16:02:11 2012] [error] [client 79.12.23.94]     main()
[Fri Mar 16 16:02:11 2012] [error] [client 79.12.23.94]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 10, in main
[Fri Mar 16 16:02:11 2012] [error] [client 79.12.23.94]     print "%s" % fs["nome"].value
[Fri Mar 16 16:02:11 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/cgi.py", line 541, in __getitem__
[Fri Mar 16 16:02:11 2012] [error] [client 79.12.23.94]     raise KeyError, key
[Fri Mar 16 16:02:11 2012] [error] [client 79.12.23.94] KeyError: 'nome'
[Fri Mar 16 16:02:11 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:02:56 2012] [error] [client 79.12.23.94] Traceback (most recent call last):
[Fri Mar 16 16:02:56 2012] [error] [client 79.12.23.94]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 15, in <module>
[Fri Mar 16 16:02:56 2012] [error] [client 79.12.23.94]     main()
[Fri Mar 16 16:02:56 2012] [error] [client 79.12.23.94]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 10, in main
[Fri Mar 16 16:02:56 2012] [error] [client 79.12.23.94]     print fs["nome"].value
[Fri Mar 16 16:02:56 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/cgi.py", line 541, in __getitem__
[Fri Mar 16 16:02:56 2012] [error] [client 79.12.23.94]     raise KeyError, key
[Fri Mar 16 16:02:56 2012] [error] [client 79.12.23.94] KeyError: 'nome'
[Fri Mar 16 16:02:56 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:02:58 2012] [error] [client 79.12.23.94] Traceback (most recent call last):
[Fri Mar 16 16:02:58 2012] [error] [client 79.12.23.94]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 15, in <module>
[Fri Mar 16 16:02:58 2012] [error] [client 79.12.23.94]     main()
[Fri Mar 16 16:02:58 2012] [error] [client 79.12.23.94]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 10, in main
[Fri Mar 16 16:02:58 2012] [error] [client 79.12.23.94]     print fs["nome"].value
[Fri Mar 16 16:02:58 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/cgi.py", line 541, in __getitem__
[Fri Mar 16 16:02:58 2012] [error] [client 79.12.23.94]     raise KeyError, key
[Fri Mar 16 16:02:58 2012] [error] [client 79.12.23.94] KeyError: 'nome'
[Fri Mar 16 16:02:58 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:07:14 2012] [error] [client 79.12.23.94] Traceback (most recent call last):
[Fri Mar 16 16:07:14 2012] [error] [client 79.12.23.94]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 15, in <module>
[Fri Mar 16 16:07:14 2012] [error] [client 79.12.23.94]     main()
[Fri Mar 16 16:07:14 2012] [error] [client 79.12.23.94]   File "/var/www/people/ltw1218/cgi-bin/prova.py", line 10, in main
[Fri Mar 16 16:07:14 2012] [error] [client 79.12.23.94]     print str(fs["nome"].value)
[Fri Mar 16 16:07:14 2012] [error] [client 79.12.23.94]   File "/usr/lib/python2.6/cgi.py", line 541, in __getitem__
[Fri Mar 16 16:07:14 2012] [error] [client 79.12.23.94]     raise KeyError, key
[Fri Mar 16 16:07:14 2012] [error] [client 79.12.23.94] KeyError: 'nome'
[Fri Mar 16 16:07:14 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:51:51 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:51:55 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:51:56 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:51:56 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:51:56 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:51:56 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:51:57 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:51:57 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:51:57 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:51:57 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:51:57 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:51:57 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:51:58 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:51:58 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:52:46 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
[Fri Mar 16 16:53:13 2012] [error] [client 79.12.23.94] File does not exist: /var/www/people/ltw1218/html/favicon.ico
